# Generated by Django 4.1.5 on 2023-01-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="turn",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_turn",
                to="play.player",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(
                choices=[
                    ("PG", "pre game"),
                    ("NG", "start of game"),
                    ("CE", "census"),
                    ("MO", "movement"),
                ],
                default="PG",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T00:48:32"),
        ),
        migrations.AlterField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="play.game",
            ),
            preserve_default=False,
        ),
    ]
