# Generated by Django 4.1.5 on 2023-01-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T16:01:10"),
        ),
    ]
