# Generated by Django 4.1.5 on 2023-01-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_game_turn_alter_game_phase_alter_game_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T00:51:45"),
        ),
        migrations.AlterField(
            model_name="game",
            name="turn",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_turn",
                to="play.player",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="play.game"
            ),
        ),
    ]
