# Generated by Django 4.1.5 on 2023-01-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0003_phase_alter_game_start_time_game_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="phase",
            field=models.CharField(default="pre game", max_length=15),
        ),
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T16:24:57"),
        ),
        migrations.DeleteModel(name="Phase",),
    ]
