# Generated by Django 4.1.5 on 2023-01-15 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0003_alter_game_start_time_alter_game_turn_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="game",),
        migrations.AddField(
            model_name="player",
            name="current_game",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="play.game"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T01:06:34"),
        ),
        migrations.AlterField(
            model_name="game",
            name="turn",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_turn",
                to="play.player",
            ),
        ),
    ]
