# Generated by Django 4.1.5 on 2023-01-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0004_alter_game_phase_alter_game_start_time_delete_phase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TerritoryOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T19:35:45"),
        ),
    ]
