# Generated by Django 4.1.5 on 2023-01-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0005_alter_game_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="start_time",
            field=models.DateTimeField(default="2023-01-15T05:39:28"),
        ),
    ]
